[#6] DB-based storage: update docker-compose configuration

diff --git a/etc/docker-entrypoint b/etc/docker-entrypoint
--- a/etc/docker-entrypoint
+++ b/etc/docker-entrypoint
@@ -2,38 +2,36 @@
 
 set -e
 
-# check that all required environment variables are set
-if [ -z "${DB_USER}" ] || [ -z "${DB_PASSWORD}" ] || [ -z "${DB_NAME}" ]; then
-  echo "Error: Required environment variables are not set" >&2
-  exit 1
-fi
-
-
 print_caption() {
+  echo ""
   echo "===================="
   echo "$1"
   echo "===================="
   echo ""
 }
 
+# check that all required environment variables are set
+if [ -z "${DB_USER}" ] || [ -z "${DB_PASSWORD}" ] || [ -z "${DB_NAME}" ]; then
+  echo "Error: Required environment variables are not set" >&2
+  exit 1
+fi
 
-if [ "${APP_SERVICE}" = "app" ]
-  then
+if [ "${APP_SERVICE}" = "app" ]; then
     print_caption "Start DB migrations"
     alembic upgrade head
     print_caption "Start app"
     python -m src.main
 
-elif [ "${APP_SERVICE}" = "test" ]
-  then
+elif [ "${APP_SERVICE}" = "test" ]; then
     print_caption "Lint check"
     export RUFF_CACHE_DIR=/tmp/.ruff
     ruff check
+    print_caption "Start DB migrations"
+    alembic upgrade head
     print_caption "Test"
-    coverage run -m pytest -o cache_dir=/tmp && \
+    coverage run -m pytest -o cache_dir=/tmp
 
-elif [ "${APP_SERVICE}" = "lint" ]
-  then
+elif [ "${APP_SERVICE}" = "lint" ]; then
     print_caption "Black check"
     black --check .
     print_caption "Lint check"
@@ -47,3 +45,5 @@ else
   kill -s SIGINT 1
 
 fi
+
+set +e
